version: "3.9"

services:
  backend:
    build: ./personal_library
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - ./personal_library/.env
    volumes:
      - ./personal_library:/app
    depends_on:
      - db

  frontend:
    build: ./frontend/book-personal_library
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - personal_library

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
